/* cmdline.h */

/* File autogenerated by gengetopt version 2.11  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "gmond"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  char * conf_arg;	/* Location of gmond configuration file (default='/etc/gmond.conf').  */
  char * location_arg;	/* Location of this host in the cluster 'rack,rank,plane'. (default='0,0,0').  */
  int debug_arg;	/* Debug level. If greater than zero, daemon will stay in foreground. (default='0').  */
  int foreground_flag;	/* Run in foreground (don't daemonize) (default=off).  */
  int default_config_flag;	/* Print the default configuration to stdout and exit (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int conf_given ;	/* Whether conf was given.  */
  int location_given ;	/* Whether location was given.  */
  int debug_given ;	/* Whether debug was given.  */
  int foreground_given ;	/* Whether foreground was given.  */
  int default_config_given ;	/* Whether default_config was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
