/* cmdline.h */

/* File autogenerated by gengetopt version 2.6  */

#ifndef _cmdline_h
#define _cmdline_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "gmond"
#ifndef VERSION
/* ******* WRITE THE VERSION OF YOUR PROGRAM HERE ******* */
#define VERSION ""
#endif

struct gengetopt_args_info {
  char * conf_arg;	/* Location of gmond configuration file (default='/etc/gmond.conf').  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int conf_given ;	/* Whether conf was given.  */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _cmdline_h */
