=pod

=head1 NAME

B<gmond.conf> - configuration file for ganglia monitoring
daemon (gmond)

=head1 DESCRIPTION

The gmond.conf file is used to configure the ganglia
monitoring daemon (gmond) which is part of the B<Ganglia
Distributed Monitoring System>.  

=head1 SECTIONS AND ATTRIBUTES

All sections and attributes are case-insensitive.  For example,
B<name> or B<NAME> or B<Name> or B<NaMe> are all equivalent.

Some sections can be included in the configuration file multiple
times and some sections are singular.  For example, you can
have only one B<cluster> section to define the attributes of
the cluster being monitored; however, you can have multiple
B<udp_recv_channel> sections to allow gmond to receive message
on multiple UDP channels.

=head2 cluster

There should only be one B<cluster> section defined.  This
section controls how gmond reports the attributes of the
cluster that it is part of.

The B<cluster> section has four attributes: B<name>,
B<owner>, B<latlong> and B<url>.

For example,

  cluster {
    name = "Millennium Cluster"
    owner = "UC Berkeley CS Dept."
    latlong = "N37.37 W122.23"
    url = "http://www.millennium.berkeley.edu/"
  }

The B<name> attributes specifies the name of the cluster of 
machines.  The B<owner> tag specifies the administrators of 
the cluster.  The pair B<name>/B<owner> should be unique
to all clusters in the world.

The B<latlong> attribute is the latitude and longitude GPS 
coordinates of this cluster on earth.  Specified to 1 mile 
accuracy with two decimal places per axis in decimal.

The B<url> for more information on the B<cluster>. 
Intended to give purpose, owner, administration, and account details 
for this cluster.

There directives directly control the XML output of gmond.  For
example, the cluster configuration example above would translate
into the following XML.

  <CLUSTER NAME="Millennium Cluster" OWNER="UC Berkeley CS Dept."
           LATLONG="N37.37 W122.23" URL="http://www.millennium.berkeley.edu/">
  ...
  </CLUSTER>

B<NOTE>: Currently gmetad cannot process data sources that do not
have a cluster tag.  This will be remedied in the future.  

=head2 host

The B<host> section provides information about the host running this
instance of B<gmond>. Currently only the B<location> string attribute is
supported. Example:

 host {
   location = "(1,2,3)"
 }

=head2 globals

The B<globals> section controls general characteristics of gmond
such as whether is should daemonize, what user it should run as,
whether is should send/receive date and such.  The B<globals>
section has the following attributes: B<daemonize>, B<setuid>, B<user>,
B<debug_level>, B<mute>, B<deaf>, B<host_dmax>, B<cleanup_threshold>,
and B<gexec>.

For example,

  globals {
    daemonize = true
    setuid = true
    user = nobody
    host_dmax = 3600
  }

The B<daemonize> attribute is a boolean.  When true, B<gmond> will 
daemonize.  When false, B<gmond> will run in the foreground.

The B<setuid> attribute is a boolean.  When true, B<gmond> will
set its effective UID to the uid of the user specified by the B<user>
attribute.  When false, B<gmond> will not change its effective user.

The B<debug_level> is an integer value.  When set to zero (0), B<gmond>
will run normally.  A B<debug_level> greater than zero will result in
B<gmond> running in the foreground and outputting debugging information.
The higher the B<debug_level> the more verbose the output.

The B<mute> attribute is a boolean.  When true, B<gmond> will not 
send data regardless of any other configuration directives.

The B<deaf> attribute is a boolean.  When true, B<gmond> will not 
receive data regardless of any other configuration directives.

The B<host_dmax> value is an integer with units in seconds.  When set 
to zero (0), B<gmond> will never delete a host from its list even when 
a remote host has stopped responding.  If B<host_dmax> is set to a
positive number then B<gmond> will flush a host after it has not heard
from it for B<host_dmax> seconds.  By the way, dmax means "delete max".

The B<cleanup_threshold> is the minimum about of time before gmond
will cleanup and hosts or metrics where B<tn> > B<dmax> a.k.a. expired
data.

The B<gexec> boolean allows you to specify whether gmond will announce
the hosts availability to run gexec jobs.  B<Note>: this requires
the B<gexecd> is running on the host and the proper keys have been
installed.  

=head2 udp_send_channel

You can define as many B<udp_send_channel> sections as you like within
the limitations of memory and file descriptors.  If B<gmond> is configured
as B<mute> this section will be ignored.

The B<udp_send_channel> has a total of five attributes: B<mcast_join>,
B<mcast_if>, B<host>, B<port> and B<ttl>.

For example, the 2.5.x version gmond would send on the following single channel
by default...

  udp_send_channel {
    mcast_join = 239.2.11.71
    port       = 8649
  }

The B<mcast_join> and B<mcast_if> attributes are optional.  When specified
B<gmond> will create the UDP socket and join the B<mcast_join> multicast group
and send data out the interface specified by B<mcast_if>.

If only a B<host> and B<port> are specified then B<gmond> will send unicast UDP
messages to the hosts specified.  You could specify multiple unicast hosts
for redundancy as B<gmond> will send UDP messages to all UDP channels.

For example...

  udp_send_channel {
    host = host.foo.com
    port = 2389
  }
  udp_send_channel {
    host = 192.168.3.4
    port = 2344
  }

would configure gmond to send messages to two hosts.  The B<host> specification
can be an IPv4/IPv6 address or a resolvable hostname.

=head2 udp_recv_channel

You can specify as many B<udp_recv_channel> sections as you like within the 
limits of memory and file descriptors.  If B<gmond> is configured B<deaf>
this attribute will be ignored.

The B<udp_recv_channel> section has following attributes:
B<mcast_join>, B<bind>, B<port>, B<mcast_if>, B<family>.  The 
B<udp_recv_channel> can also have an B<acl> definition (see
ACCESS CONTROL LISTS below).

For example, the 2.5.x gmond ran with a single udp receive channel...

  udp_recv_channel {
    mcast_join = 239.2.11.71
    bind       = 239.2.11.71
    port       = 8649
  }

The B<mcast_join> and B<mcast_if> should only be used if you want to 
have this UDP channel receive multicast packets the multicast
group B<mcast_join> on interface B<mcast_if>.  If you do not specify
multicast attributes then B<gmond> will simply create a UDP server
on the specified B<port>.

You can use the B<bind> attribute to bind to a particular local address.

The family address is set to B<inet4> by default.  If you want to bind
the port to an B<inet6> port, you need to specify that in the family
attribute.  Ganglia will not allow IPV6=>IPV4 mapping (for portability
and security reasons).  If you want to listen on both B<inet4> and
B<inet6> for a particular port, explicitly state it with the following:

  udp_recv_channel {
    port = 8666
    family = inet4
  }
  udp_recv_channel {
    port = 8666
    family = inet6
  }

If you specify a bind address, the family of that address takes precedence.
f your IPv6 stack doesn't support IPV6_V6ONLY, a warning will be issued
but gmond will continue working (this should rarely happen).

Multicast Note: for multicast, specifying a B<bind> address that equals the B<mcast_join>
address will prevent unicast UDP messages to the same B<port> from being 
processed.

=head2 tcp_accept_channel

You can specify as many B<tcp_accept_channel> sections as you like
within the limitations of memory and file descriptors.  If B<gmond>
is configured to be B<mute>, then these sections are ignored.

The B<tcp_accept_channel> has the following attributes: B<bind>, B<port>, 
B<interface>, B<family> and B<timeout>.  A B<tcp_accept_channel> may also have
an B<acl> section specified (see ACCESS CONTROL LISTS below).

For example, 2.5.x gmond would accept connections on a single TCP
channel.

  tcp_accept_channel {
    port = 8649
  }

The B<bind> address is optional and allows you to specify which 
local address B<gmond> will bind to for this channel.

The B<port> is an integer than specifies which port to answer 
requests for data.

The B<family> address is set to B<inet4> by default.  If you want to bind
the port to an B<inet6> port, you need to specify that in the family
attribute.  Ganglia will not allow IPV6=>IPV4 mapping (for portability
and security reasons).  If you want to listen on both B<inet4> and
B<inet6> for a particular port, explicitly state it with the following:

  tcp_accept_channel {
    port = 8666
    family = inet4
  }
  tcp_accept_channel {
    port = 8666
    family = inet6
  }

If you specify a bind address, the family of that address takes precedence.
If your IPv6 stack doesn't support IPV6_V6ONLY, a warning will be issued
but gmond will continue working (this should rarely happen).

The B<timeout> attribute allows you to specify how many microseconds to block before
closing a connection to a client.  The default is set to 1 second (1000000 usecs).  
If you have a very slow connection you may need to increase this value.

The B<interface> is not implemented at this time (use B<bind>).

=head2 collection_group

You can specify as many B<collection_group> section as you like
within the limitations of memory.  A B<collection_group> has
the following attributes: B<collect_once>, B<collect_every>
and B<time_threshold>.  A B<collection_group> must also contain one
or more B<metric> sections.

The B<metric> section has the following attributes: B<name> and
B<value_threshold>.  For a list of available metric names, run
the following command:

  % gmond -m

Here is an example of a collection group for a static metric...

  collection_group {
    collect_once   = yes
    time_threshold = 1800
    metric {
     name = "cpu_num"
    }
  }

This B<collection_group> entry would cause gmond to collect the 
B<cpu_num> metric once at startup (since the number of CPUs will not 
change between reboots).  The metric B<cpu_num> would be send
every 1/2 hour (1800 seconds).  The default value for the B<time_threshold>
is 3600 seconds if no B<time_threshold> is specified.

The B<time_threshold> is the maximum
amount of time that can pass before gmond sends all B<metric>s specified in the
B<collection_group> to all listed B<udp_send_channel>s.  A
B<metric> may be sent before this B<time_threshold> is met if
during collection the value surpasses the B<value_threshold> (explained
below).

Here is an example of a collection group for a volatile metric...

  collection_group {
    collect_every = 60
    time_threshold = 300
    metric {
      name = "cpu_user"
      value_threshold = 5.0
    }
    metric {
      name = "cpu_idle"
      value_threshold = 10.0
    }
  }

This collection group would collect the B<cpu_user> and B<cpu_idle> metrics
every 60 seconds (specified in B<collect_every>).  If B<cpu_user> varies by
5.0% or B<cpu_idle> varies by 10.0%, then the entire B<collection_group>
is sent.  If no B<value_threshold> is triggered within B<time_threshold>
seconds (in this case 300), the entire B<collection_group> is sent.

Each time the metric value
is collected the new value is compared with the old value collected.  If
the difference between the last value and current value is greater than
the B<value_threshold>, the entire collection group is send to the 
B<udp_send_channel>s defined.

It's important to note that all metrics in a collection group are sent
even when only a single B<value_threshold> is surpassed.

=head2 include

Useful if you want to include another configuration file; for example:

  include("globals.conf")

  udp_send_channel {
    mcast_join = 239.2.11.71
    port       = 8649
  }

=head1 ACCESS CONTROL

The B<udp_recv_channel> and B<tcp_accept_channel> directives
can contain an Access Control List (ACL).  This ACL allows you to specify
exactly which hosts gmond process data from.

An example of an B<acl> entry looks like

  acl {
    default = "deny"
    access {
      ip = 192.168.0.4
      mask = 32
      action = "allow"
    }
  }

This ACL will by default reject all traffic that is not specifically from
host 192.168.0.4 (the mask size for an IPv4 address is 32, the mask size
for an IPv6 address is 128 to represent a single host).

Here is another example

  acl {
    default = "allow"
    access {
      ip = 192.168.0.0
      mask = 24
      action = "deny"
    }
    access {
      ip = ::ff:1.2.3.0
      mask = 120
      action = "deny"
    }
  }

This ACL will by default allow all traffic unless it comes from the 
two subnets specified with action = "deny".
    


=head1 EXAMPLE

The default behavior for a 2.5.x gmond would be specified as...

  udp_recv_channel {
    mcast_join = 239.2.11.71
    bind       = 239.2.11.71
    port       = 8649
  }
  udp_send_channel {
    mcast_join = 239.2.11.71
    port       = 8649
  }
  tcp_accept_channel {
    port       = 8649
  }

To see the complete default configuration for gmond simply run:

  % gmond -t

gmond will print out it default behavior in a configuration file
and then exit.  Capturing this output to a file can serve as
a useful starting point for creating your own custom configuration.

  % gmond -t > custom.conf

edit B<custom.conf> to taste and then

  % gmond -c ./custom.conf

=head1 NOTES

The ganglia web site is at http://ganglia.info/.

=head1 COPYRIGHT

Copyright (c) 2005 The University of California, Berkeley

=cut
