#!/bin/sh
# $Id$
echo "Bootstrapping libmetrics"
cd srclib/libmetrics && ./bootstrap
cd ../..

echo "Create distribution timestamp"
touch Makefile.am
echo "Running make distclean"  
make distclean   
echo "Running aclocal"  &&
aclocal   &&
echo "Running autoheader"  &&
autoheader  &&
echo "Running automake"  &&
automake --add-missing --copy  &&
echo "Running autoconf"  &&
autoconf  &&
echo  &&
echo  &&
echo "To begin installation, run \"./configure\" now" 
