#!/bin/sh

GANGLIA_HOME=${CLIENT_BASEDIR}
GANGLIA_ETC=${GANGLIA_HOME}/etc


smf=no
if [ -f /usr/sbin/svccfg -a -f /usr/sbin/svcadm ]
  then
  smf=yes
fi

if [ $smf = yes ]
then
    /usr/sbin/svcadm disable svc:/ganglia/gmond
else
    if [ -f /etc/init.d/gmond ];
    then

        /etc/init.d/gmond stop >/dev/null 2>&1

    fi
fi


exit 0

