#!/bin/sh
# $Id$
if [ -d ../autotools ]; then
	PATH=../autotools/bin:${PATH}
fi
echo "Running make distclean"  
make distclean   
echo "Running aclocal"  &&
aclocal   &&
echo "Running autoheader"  &&
autoheader  &&
echo "Running automake"  &&
automake --add-missing --copy  &&
echo "Running autoconf"  &&
autoconf  &&
echo  &&
echo  &&
echo "To begin installation, run \"./configure\" now" 
