/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  /usr/bin/gengetopt --input ./cmdline.sh 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "The Ganglia Status Client (gstat) connects with a \nGanglia Monitoring Daemon (gmond) and outputs a load-balanced list \nof hosts";

const char *gengetopt_args_info_usage = "Usage: gstat [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help             Print help and exit",
  "  -V, --version          Print version and exit",
  "  -a, --all              List all hosts.  Not just hosts running gexec  \n                           (default=off)",
  "  -d, --dead             Print only the hosts which are dead  (default=off)",
  "  -m, --mpifile          Print a load-balanced mpifile  (default=off)",
  "  -1, --single_line      Print host and information all on one line  \n                           (default=off)",
  "  -l, --list             Print ONLY the host list  (default=off)",
  "  -n, --numeric          Print numeric addresses instead of hostnames  \n                           (default=off)",
  "  -i, --gmond_ip=STRING  Specify the ip address of the gmond to query  \n                           (default=`localhost')",
  "  -p, --gmond_port=INT   Specify the gmond port to query  (default=`8649')",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->all_given = 0 ;
  args_info->dead_given = 0 ;
  args_info->mpifile_given = 0 ;
  args_info->single_line_given = 0 ;
  args_info->list_given = 0 ;
  args_info->numeric_given = 0 ;
  args_info->gmond_ip_given = 0 ;
  args_info->gmond_port_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->all_flag = 0;
  args_info->dead_flag = 0;
  args_info->mpifile_flag = 0;
  args_info->single_line_flag = 0;
  args_info->list_flag = 0;
  args_info->numeric_flag = 0;
  args_info->gmond_ip_arg = gengetopt_strdup ("localhost");
  args_info->gmond_ip_orig = NULL;
  args_info->gmond_port_arg = 8649;
  args_info->gmond_port_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->all_help = gengetopt_args_info_help[2] ;
  args_info->dead_help = gengetopt_args_info_help[3] ;
  args_info->mpifile_help = gengetopt_args_info_help[4] ;
  args_info->single_line_help = gengetopt_args_info_help[5] ;
  args_info->list_help = gengetopt_args_info_help[6] ;
  args_info->numeric_help = gengetopt_args_info_help[7] ;
  args_info->gmond_ip_help = gengetopt_args_info_help[8] ;
  args_info->gmond_port_help = gengetopt_args_info_help[9] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->gmond_ip_arg));
  free_string_field (&(args_info->gmond_ip_orig));
  free_string_field (&(args_info->gmond_port_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->all_given)
    write_into_file(outfile, "all", 0, 0 );
  if (args_info->dead_given)
    write_into_file(outfile, "dead", 0, 0 );
  if (args_info->mpifile_given)
    write_into_file(outfile, "mpifile", 0, 0 );
  if (args_info->single_line_given)
    write_into_file(outfile, "single_line", 0, 0 );
  if (args_info->list_given)
    write_into_file(outfile, "list", 0, 0 );
  if (args_info->numeric_given)
    write_into_file(outfile, "numeric", 0, 0 );
  if (args_info->gmond_ip_given)
    write_into_file(outfile, "gmond_ip", args_info->gmond_ip_orig, 0);
  if (args_info->gmond_port_given)
    write_into_file(outfile, "gmond_port", args_info->gmond_port_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "all",	0, NULL, 'a' },
        { "dead",	0, NULL, 'd' },
        { "mpifile",	0, NULL, 'm' },
        { "single_line",	0, NULL, '1' },
        { "list",	0, NULL, 'l' },
        { "numeric",	0, NULL, 'n' },
        { "gmond_ip",	1, NULL, 'i' },
        { "gmond_port",	1, NULL, 'p' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVadm1lni:p:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'a':	/* List all hosts.  Not just hosts running gexec.  */
        
        
          if (update_arg((void *)&(args_info->all_flag), 0, &(args_info->all_given),
              &(local_args_info.all_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "all", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Print only the hosts which are dead.  */
        
        
          if (update_arg((void *)&(args_info->dead_flag), 0, &(args_info->dead_given),
              &(local_args_info.dead_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "dead", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Print a load-balanced mpifile.  */
        
        
          if (update_arg((void *)&(args_info->mpifile_flag), 0, &(args_info->mpifile_given),
              &(local_args_info.mpifile_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "mpifile", 'm',
              additional_error))
            goto failure;
        
          break;
        case '1':	/* Print host and information all on one line.  */
        
        
          if (update_arg((void *)&(args_info->single_line_flag), 0, &(args_info->single_line_given),
              &(local_args_info.single_line_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "single_line", '1',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Print ONLY the host list.  */
        
        
          if (update_arg((void *)&(args_info->list_flag), 0, &(args_info->list_given),
              &(local_args_info.list_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "list", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Print numeric addresses instead of hostnames.  */
        
        
          if (update_arg((void *)&(args_info->numeric_flag), 0, &(args_info->numeric_given),
              &(local_args_info.numeric_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "numeric", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Specify the ip address of the gmond to query.  */
        
        
          if (update_arg( (void *)&(args_info->gmond_ip_arg), 
               &(args_info->gmond_ip_orig), &(args_info->gmond_ip_given),
              &(local_args_info.gmond_ip_given), optarg, 0, "localhost", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "gmond_ip", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Specify the gmond port to query.  */
        
        
          if (update_arg( (void *)&(args_info->gmond_port_arg), 
               &(args_info->gmond_port_orig), &(args_info->gmond_port_given),
              &(local_args_info.gmond_port_given), optarg, 0, "8649", ARG_INT,
              check_ambiguity, override, 0, 0,
              "gmond_port", 'p',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
