/*
  File autogenerated by gengetopt version 2.11
  generated with the following command:
  /usr/bin/gengetopt --input ./cmdline.sh 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "lib/getopt.h"

#include "cmdline.h"

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
  "Purpose:\n"
  "  The Ganglia Metric Client (gmetric) announces a metric\n"
  "  value to all Ganglia Monitoring Daemons (gmonds) that are listening\n"
  "  on the cluster multicast channel.\n"
  "\n"
  "Usage: %s [OPTIONS]...\n", CMDLINE_PARSER_PACKAGE);
  printf("\n");
  printf("  -h, --help                  Print help and exit\n");
  printf("  -V, --version               Print version and exit\n");
  printf("  -n, --name=STRING           Name of the metric\n");
  printf("  -v, --value=STRING          Value of the metric\n");
  printf("  -t, --type=STRING           Either \n                                string|int8|uint8|int16|uint16|int32|uint32|float|double\n");
  printf("  -u, --units=STRING          Unit of measure for the value e.g. Kilobytes, \n                                Celcius\n");
  printf("  -s, --slope=STRING          Either zero|positive|negative|both  (default=\n                                `both')\n");
  printf("  -x, --tmax=INT              The maximum time in seconds between gmetric \n                                calls  (default=`60')\n");
  printf("  -d, --dmax=INT              The lifetime in seconds of this metric  (default=\n                                `0')\n");
  printf("  -c, --msg_channel=STRING    Message channel  (default=`239.2.11.71')\n");
  printf("  -p, --msg_port=STRING       Message port  (default=`8649')\n");
  printf("  -i, --msg_if=STRING         Message interface e.g. 'eth1'  (default=`kernel \n                                decides')\n");
  printf("  -l, --msg_ttl=INT           Message Time-To-Live (TTL)  (default=`1')\n");
  printf("  -k, --mcast_channel=STRING  Multicast channel to send/receive on  (default=\n                                `239.2.11.71')\n");
  printf("  -o, --mcast_port=STRING     Multicast port to send/receive on  (default=\n                                `8649')\n");
  printf("  -f, --mcast_if=STRING       Multicast interface e.g. 'eth1'  (default=\n                                `kernel decides')\n");
  printf("  -j, --mcast_ttl=INT         Multicast Time-To-Live (TTL)  (default=`1')\n");
}


static char *gengetopt_strdup (const char *s);

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->name_given = 0 ;
  args_info->value_given = 0 ;
  args_info->type_given = 0 ;
  args_info->units_given = 0 ;
  args_info->slope_given = 0 ;
  args_info->tmax_given = 0 ;
  args_info->dmax_given = 0 ;
  args_info->msg_channel_given = 0 ;
  args_info->msg_port_given = 0 ;
  args_info->msg_if_given = 0 ;
  args_info->msg_ttl_given = 0 ;
  args_info->mcast_channel_given = 0 ;
  args_info->mcast_port_given = 0 ;
  args_info->mcast_if_given = 0 ;
  args_info->mcast_ttl_given = 0 ;
#define clear_args() { \
  args_info->name_arg = NULL; \
  args_info->value_arg = NULL; \
  args_info->type_arg = NULL; \
  args_info->units_arg = NULL; \
  args_info->slope_arg = gengetopt_strdup("both") ;\
  args_info->tmax_arg = 60 ;\
  args_info->dmax_arg = 0 ;\
  args_info->msg_channel_arg = gengetopt_strdup("239.2.11.71") ;\
  args_info->msg_port_arg = gengetopt_strdup("8649") ;\
  args_info->msg_if_arg = gengetopt_strdup("kernel decides") ;\
  args_info->msg_ttl_arg = 1 ;\
  args_info->mcast_channel_arg = gengetopt_strdup("239.2.11.71") ;\
  args_info->mcast_port_arg = gengetopt_strdup("8649") ;\
  args_info->mcast_if_arg = gengetopt_strdup("kernel decides") ;\
  args_info->mcast_ttl_arg = 1 ;\
}

  clear_args();

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "name",	1, NULL, 'n' },
        { "value",	1, NULL, 'v' },
        { "type",	1, NULL, 't' },
        { "units",	1, NULL, 'u' },
        { "slope",	1, NULL, 's' },
        { "tmax",	1, NULL, 'x' },
        { "dmax",	1, NULL, 'd' },
        { "msg_channel",	1, NULL, 'c' },
        { "msg_port",	1, NULL, 'p' },
        { "msg_if",	1, NULL, 'i' },
        { "msg_ttl",	1, NULL, 'l' },
        { "mcast_channel",	1, NULL, 'k' },
        { "mcast_port",	1, NULL, 'o' },
        { "mcast_if",	1, NULL, 'f' },
        { "mcast_ttl",	1, NULL, 'j' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVn:v:t:u:s:x:d:c:p:i:l:k:o:f:j:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'n':	/* Name of the metric.  */
          if (args_info->name_given)
            {
              fprintf (stderr, "%s: `--name' (`-n') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->name_given = 1;
          args_info->name_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* Value of the metric.  */
          if (args_info->value_given)
            {
              fprintf (stderr, "%s: `--value' (`-v') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->value_given = 1;
          args_info->value_arg = gengetopt_strdup (optarg);
          break;

        case 't':	/* Either string|int8|uint8|int16|uint16|int32|uint32|float|double.  */
          if (args_info->type_given)
            {
              fprintf (stderr, "%s: `--type' (`-t') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->type_given = 1;
          args_info->type_arg = gengetopt_strdup (optarg);
          break;

        case 'u':	/* Unit of measure for the value e.g. Kilobytes, Celcius.  */
          if (args_info->units_given)
            {
              fprintf (stderr, "%s: `--units' (`-u') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->units_given = 1;
          args_info->units_arg = gengetopt_strdup (optarg);
          break;

        case 's':	/* Either zero|positive|negative|both.  */
          if (args_info->slope_given)
            {
              fprintf (stderr, "%s: `--slope' (`-s') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->slope_given = 1;
          if (args_info->slope_arg)
            free (args_info->slope_arg); /* free default string */
          args_info->slope_arg = gengetopt_strdup (optarg);
          break;

        case 'x':	/* The maximum time in seconds between gmetric calls.  */
          if (args_info->tmax_given)
            {
              fprintf (stderr, "%s: `--tmax' (`-x') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->tmax_given = 1;
          args_info->tmax_arg = strtol (optarg,&stop_char,0);
          break;

        case 'd':	/* The lifetime in seconds of this metric.  */
          if (args_info->dmax_given)
            {
              fprintf (stderr, "%s: `--dmax' (`-d') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->dmax_given = 1;
          args_info->dmax_arg = strtol (optarg,&stop_char,0);
          break;

        case 'c':	/* Message channel.  */
          if (args_info->msg_channel_given)
            {
              fprintf (stderr, "%s: `--msg_channel' (`-c') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->msg_channel_given = 1;
          if (args_info->msg_channel_arg)
            free (args_info->msg_channel_arg); /* free default string */
          args_info->msg_channel_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* Message port.  */
          if (args_info->msg_port_given)
            {
              fprintf (stderr, "%s: `--msg_port' (`-p') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->msg_port_given = 1;
          if (args_info->msg_port_arg)
            free (args_info->msg_port_arg); /* free default string */
          args_info->msg_port_arg = gengetopt_strdup (optarg);
          break;

        case 'i':	/* Message interface e.g. 'eth1'.  */
          if (args_info->msg_if_given)
            {
              fprintf (stderr, "%s: `--msg_if' (`-i') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->msg_if_given = 1;
          if (args_info->msg_if_arg)
            free (args_info->msg_if_arg); /* free default string */
          args_info->msg_if_arg = gengetopt_strdup (optarg);
          break;

        case 'l':	/* Message Time-To-Live (TTL).  */
          if (args_info->msg_ttl_given)
            {
              fprintf (stderr, "%s: `--msg_ttl' (`-l') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->msg_ttl_given = 1;
          args_info->msg_ttl_arg = strtol (optarg,&stop_char,0);
          break;

        case 'k':	/* Multicast channel to send/receive on.  */
          if (args_info->mcast_channel_given)
            {
              fprintf (stderr, "%s: `--mcast_channel' (`-k') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->mcast_channel_given = 1;
          if (args_info->mcast_channel_arg)
            free (args_info->mcast_channel_arg); /* free default string */
          args_info->mcast_channel_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Multicast port to send/receive on.  */
          if (args_info->mcast_port_given)
            {
              fprintf (stderr, "%s: `--mcast_port' (`-o') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->mcast_port_given = 1;
          if (args_info->mcast_port_arg)
            free (args_info->mcast_port_arg); /* free default string */
          args_info->mcast_port_arg = gengetopt_strdup (optarg);
          break;

        case 'f':	/* Multicast interface e.g. 'eth1'.  */
          if (args_info->mcast_if_given)
            {
              fprintf (stderr, "%s: `--mcast_if' (`-f') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->mcast_if_given = 1;
          if (args_info->mcast_if_arg)
            free (args_info->mcast_if_arg); /* free default string */
          args_info->mcast_if_arg = gengetopt_strdup (optarg);
          break;

        case 'j':	/* Multicast Time-To-Live (TTL).  */
          if (args_info->mcast_ttl_given)
            {
              fprintf (stderr, "%s: `--mcast_ttl' (`-j') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->mcast_ttl_given = 1;
          args_info->mcast_ttl_arg = strtol (optarg,&stop_char,0);
          break;


        case 0:	/* Long option with no short option */

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (EXIT_FAILURE);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", CMDLINE_PARSER_PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */


  if (! args_info->name_given)
    {
      fprintf (stderr, "%s: '--name' ('-n') option required\n", CMDLINE_PARSER_PACKAGE);
      missing_required_options = 1;
    }
  if (! args_info->value_given)
    {
      fprintf (stderr, "%s: '--value' ('-v') option required\n", CMDLINE_PARSER_PACKAGE);
      missing_required_options = 1;
    }
  if (! args_info->type_given)
    {
      fprintf (stderr, "%s: '--type' ('-t') option required\n", CMDLINE_PARSER_PACKAGE);
      missing_required_options = 1;
    }
  if ( missing_required_options )
    exit (EXIT_FAILURE);

  return 0;
}
