#!/bin/sh
# $Id: bootstrap 388 2004-11-18 02:24:06Z massie $
if [ -d ../autotools ]; then
	PATH=../autotools/bin:${PATH}
fi
#echo "Running make distclean"  
#make distclean   
echo "Running aclocal"  &&
aclocal   &&
echo "Running autoheader"  &&
autoheader  &&
echo "Running automake"  &&
automake --add-missing --copy  &&
echo "Running autoconf"  &&
autoconf  &&
echo
