#!/bin/sh
# $Id$
#echo "Running make distclean"  
#make distclean   
echo "Running aclocal" &&
aclocal &&
echo "Running autoheader" &&
autoheader &&
echo "Running libtoolize" &&
mkdir -p build && libtoolize --copy &&
echo "Running automake" &&
automake --add-missing --copy &&
echo "Running autoconf" &&
autoconf &&
echo
