#!/bin/sh
#echo "Running make distclean"
#make distclean
echo "Running aclocal" &&
aclocal &&
echo "Running autoheader" &&
autoheader &&
echo "Preparing tree" &&
mkdir -p build && 
echo "Running automake" &&
automake --add-missing --copy --foreign 2>/dev/null
echo "Running libtoolize" &&
libtoolize --automake --copy && automake --add-missing --copy --foreign &&
echo "Running autoconf" &&
autoconf -f || exit 1
echo
