#!/bin/sh
# $Id$
#echo "Running make distclean"
#make distclean
echo "Running aclocal" &&
aclocal &&
echo "Running autoheader" &&
autoheader &&
echo "Preparing tree" &&
mkdir -p build && touch ChangeLog && ../scripts/svn2cl.sh -i --break-before-msg=1 --reparagraph
echo "Running automake" &&
automake --add-missing --copy 2>/dev/null
echo "Running libtoolize" &&
libtoolize --automake --copy && automake --add-missing --copy &&
echo "Running autoconf" &&
autoconf &&
echo
