/* cmdline.h */

/* File autogenerated by gengetopt version 2.7.1  */

#ifndef _cmdline_h
#define _cmdline_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#ifndef PACKAGE
#define PACKAGE "gmetad"
#endif

#ifndef VERSION
#define VERSION ""
#endif

struct gengetopt_args_info
{
  char * conf_arg;	/* Location of gmetad configuration file (default='/etc/ganglia/gmetad.conf').  */
  int debug_arg;	/* Debug level. If greater than zero, daemon will stay in foreground. (default=0).  */
  char * pid_file_arg;	/* file to write a pid to */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int conf_given ;	/* Whether conf was given.  */
  int debug_given ;	/* Whether debug was given.  */
  int pid_file_given ;	/* Whether a file for writing a pid to was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _cmdline_h */
