#ifndef GMETAD_TYPEDEFS_H
#define GMETAD_TYPEDEFS_H 1 

/* This was taken from metric_hash.c which was
   generated by gperf */
#define MAX_HASH_VALUE 97

#include <ganglia/net.h> 

typedef struct
   {
      char *name;
      unsigned int num_sources;
      g_inet_addr **sources;
   }
data_source_list_t;

#ifndef SYS_CALL
#define SYS_CALL(RC,SYSCALL) \
   do {                      \
       RC = SYSCALL;         \
   } while (RC < 0 && errno == EINTR);
#endif

enum data_type
   {
      Unknown,
      String,
      Int8,
      Uint8,
      Int16,
      Uint16, 
      Int32,
      Uint32,
      Float,
      Double,
      Timestamp
   };

typedef struct
   {
      enum data_type Type;
      union
         {
            char *String;
            char Int8;
            unsigned char Uint8;
            short Int16;
            unsigned short Uint16;
            long  Int32;
            unsigned long Uint32;
            float Float;
            double Double;
            unsigned long Timestamp;
         } data;
      /* Either Text or data.String
         is returned depending on the 
         Type.
       */
      char Text[16];
   }  Value;

 
          
           


#endif
