/* cmdline.h */

/* File autogenerated by gengetopt version 2.6  */

#ifndef _cmdline_h
#define _cmdline_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "gstat"
#ifndef VERSION
/* ******* WRITE THE VERSION OF YOUR PROGRAM HERE ******* */
#define VERSION ""
#endif

struct gengetopt_args_info {
  int all_flag;	/* List all hosts.  Not just hosts running gexec (default=off).  */
  int dead_flag;	/* Print only the hosts which are dead (default=off).  */
  int mpifile_flag;	/* Print a load-balanced mpifile (default=off).  */
  int single_line_flag;	/* Print host and information all on one line (default=off).  */
  int list_flag;	/* Print ONLY the host list (default=off).  */
  char * gmond_ip_arg;	/* Specify the ip address of the gmond to query (default='127.0.0.1').  */
  int gmond_port_arg;	/* Specify the gmond port to query (default=8649).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int all_given ;	/* Whether all was given.  */
  int dead_given ;	/* Whether dead was given.  */
  int mpifile_given ;	/* Whether mpifile was given.  */
  int single_line_given ;	/* Whether single_line was given.  */
  int list_given ;	/* Whether list was given.  */
  int gmond_ip_given ;	/* Whether gmond_ip was given.  */
  int gmond_port_given ;	/* Whether gmond_port was given.  */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _cmdline_h */
