/* cmdline.h */

/* File autogenerated by gengetopt version 2.11  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "gstat"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  int all_flag;	/* List all hosts.  Not just hosts running gexec (default=off).  */
  int dead_flag;	/* Print only the hosts which are dead (default=off).  */
  int mpifile_flag;	/* Print a load-balanced mpifile (default=off).  */
  int single_line_flag;	/* Print host and information all on one line (default=off).  */
  int list_flag;	/* Print ONLY the host list (default=off).  */
  char * gmond_ip_arg;	/* Specify the ip address of the gmond to query (default='localhost').  */
  int gmond_port_arg;	/* Specify the gmond port to query (default='8649').  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int all_given ;	/* Whether all was given.  */
  int dead_given ;	/* Whether dead was given.  */
  int mpifile_given ;	/* Whether mpifile was given.  */
  int single_line_given ;	/* Whether single_line was given.  */
  int list_given ;	/* Whether list was given.  */
  int gmond_ip_given ;	/* Whether gmond_ip was given.  */
  int gmond_port_given ;	/* Whether gmond_port was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
