#!/bin/sh
# $Id$
echo "Running make distclean"  
make distclean   
echo "Running aclocal"  &&
aclocal   &&
echo "Running autoheader"  &&
autoheader  &&
echo "Running automake"  &&
automake --add-missing  &&
echo "Running autoconf"  &&
autoconf  &&
echo  &&
echo  &&
echo "To begin installation, run \"./configure\" now" 
